skip_commits:
  message: /((Create.*\.md)|(Update.*\.md))/

version: 0.0.2.{build}

configuration: Debug

environment:
  sourcesFolder: src
  solutionName: photosphere-search-engine.sln
  projectName: Photosphere.SearchEngine

image: Visual Studio 2017

assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "{version}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"

before_build:
  - cd %sourcesFolder%
  - nuget restore
  - cd ..

build:
  verbosity: minimal
  project: $(sourcesFolder)\$(solutionName)
